### PR TITLE
Add customization note

### PR DESCRIPTION
**Pull request by d-m-u**
Include note about how to run this on select repos since I keep hearing about how people mostly only need it run on a couple, not the whole hog, and I omitted pictures of the snake only under the greatest reluctance.

### CODE REVIEW

**Comment by d-m-u** [comment]
@tinaafitz please review

**Comment by d-m-u** [comment]
@miq-bot add_label documentation

**Comment by d-m-u** [comment]
@miq-bot add_reviewer @tinaafitz

**Comment by d-m-u** [comment]
I guess maybe the bot doesn't like me anymore

**Comment by JPrause** [comment]
Oopsy, I didn't mean to remove @tinaafitz as reviewer. Next time I'll know to press "That" button. Ha!

**Comment by d-m-u** [comment]
@tinaafitz it'd be real great to get your eyes on this.

**Comment by d-m-u** [comment]
anyone want to look at this?

**Comment by JPrause** [comment]
So this was reviewed and approved, but then closed. Why?
There was no code change here,..only an update to the README file, which IMHO, added value.
I was also going to ping to get this merged.

**Comment by d-m-u** [comment]
It's never gonna be used and doesn't matter, that's why.

**Comment by JPrause** [comment]
au contraire, I would use it. Please reopen the PR please.

**Comment by JPrause** [comment]
Thanks! :+1:

**Comment by JPrause** [comment]
@bdunne can you merge this approved PR.

**Pull request merged**
