### PR TITLE
Remove no longer used scripts

### PR DESCRIPTION
**Pull request by chessbyte**

### CODE REVIEW

**Comment by bdunne** [comment]
@jvlcek @tinaafitz @gmcculloug Are any of you using these?

**Comment by jvlcek** [comment]
> @jvlcek @tinaafitz @gmcculloug Are any of you using these?

I am not aware of them being used.

**Comment by gmcculloug** [comment]
No, I don't use them.

**Comment by tinaafitz** [comment]
No, I don't use them.

**Pull request merged**
